  - name: Configure elk VM with Docker
    hosts: elk
    remote_user: azadmin
    become: true
    tasks:

    - name: use more memory
      sysctl:
         name: vm.max_map_count
         value: '262144'
         state: present
         reload: yes

    - name: Uninstall apache
      apt:
        name: apache2
        state: absent

    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container
      docker_container:
        restart_policy: always
        name: elk
        image: sebp/elk:761
        state: started
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable docker service on boot
      systemd:
        name: docker
        enabled: yes
